name: Build

on:
  push:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.7"

      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          args: --timeout 3m --verbose --exclude-dirs lsp

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Docker to 28.0.1
        run: |
          sudo systemctl stop docker.service
          sudo apt-get purge docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin
          sudo apt-get install curl
          curl -fsSL https://test.docker.com -o get-docker.sh
          sudo sh ./get-docker.sh --version 28.0.1

      - uses: docker/setup-buildx-action@v3
        with:
          use: true

      - run: docker build -t docker/lsp:test --target test .

      - run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock docker/lsp:test make test

  upload:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
        include:
          - os: windows
            ext: .exe
          - os: linux
            ext: ""
          - os: darwin
            ext: ""

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.7"

      - name: Build for ${{ matrix.os }}-${{ matrix.arch }}
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make build

      - uses: actions/upload-artifact@v4
        with:
          name: docker-language-server-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
          path: docker-language-server-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
          if-no-files-found: error
