name: Prepare release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: Version type
        required: true
        default: minor
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Configure Git
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"

      - name: Update changelog to the next ${{ github.event.inputs.version_type }} version
        run: |
          go run ./releaser/main.go update-changelog ${{ github.event.inputs.version_type }}

      - name: Extract new version from changelog
        id: version
        # Extract the version from the first ## header in CHANGELOG.md
        run: |
          NEW_VERSION=$(grep -m 1 "^## \[" CHANGELOG.md | sed 's/^## \[\([^]]*\)\].*/\1/')
          echo "New version (${{ github.event.inputs.version_type }}): $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create pull request
        # https://github.com/peter-evans/create-pull-request/releases/tag/v7.0.8
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: bot/prepare-release-v${{ steps.version.outputs.new_version }}
          commit-message: |
            Prepare for the v${{ steps.version.outputs.new_version }} release

            This commit was generated by a GitHub Action workflow. It was triggered
            by ${{ github.actor }}.
          signoff: true
          delete-branch: true
          title: "Prepare for the v${{ steps.version.outputs.new_version }} release (triggered by ${{ github.actor }})"
          body: |
            This pull request was generated by `./github/workflows/prepare-release.yml`.
          draft: false
          add-paths: CHANGELOG.md
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
